const NON_LEXICAL_WORD_AUTH_USERNAME = 'vaitrade';
const NON_LEXICAL_WORD_AUTH_PASSWORD = 'vai123';
const DB_USERNAME = 'vaitrade';
const DB_PASSWORD = 'vai123';

module.exports = {
    NON_LEXICAL_WORD_AUTH_USERNAME,
    NON_LEXICAL_WORD_AUTH_PASSWORD,
    DB_USERNAME,
    DB_PASSWORD
}